pipeline {
    agent any

    environment {
        IMAGE_NAME = "saathi-backend"
        DOCKER_HUB_REPO = "satvik0100/saathi-backend"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    tools {
        maven 'jenkins-maven'
    }

    triggers {
        cron('H * * * *')
    }

    stages {
        stage('Build Maven') {
            steps {
                dir('Saathi-Backend') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
    }

    post {
        success {
            echo "✅ CI pipeline complete for Saathi build #${BUILD_NUMBER}"
        }
        failure {
            echo "❌ Build failed for Saathi build #${BUILD_NUMBER}"
        }
    }
}
